# Generated by Django 5.0.4 on 2024-05-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts_manager', '0011_alter_user_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cover_picture', models.ImageField(default='static_files/images/default_coures_image.png', upload_to='images/course_cover_pic')),
                ('catagory', models.CharField(choices=[('MATH', 'Mathematics'), ('ENG', 'English'), ('SCI', 'Science'), ('HIST', 'History'), ('CS', 'Computer Science'), ('BIO', 'Biology'), ('CHEM', 'Chemistry'), ('PHY', 'Physics'), ('PY', 'Python Programming'), ('CPP', 'C++ Programming'), ('DSL', 'Data Structures and Algorithms'), ('GO', 'Go Programming'), ('JAVA', 'Java Programming')], max_length=30)),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='coures_i_took', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_coures', to='user_accounts_manager.instructorsprofile')),
            ],
        ),
    ]
