# Generated by Django 5.0.4 on 2024-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_picture',
            field=models.ImageField(blank=True, default='static_files/images/default_coures_image.png', upload_to='images/course_cover_pic'),
        ),
    ]
