# Generated by Django 5.0.4 on 2024-05-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_varifaied',
            field=models.BooleanField(default=False),
        ),
    ]
