# Generated by Django 5.0.4 on 2024-05-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_manager', '0002_user_email_is_varifaied'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
