# Generated by Django 5.0.4 on 2024-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_manager', '0003_user_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'student'), ('instructors', 'instructors'), ('administrator', 'administrator')], default='student', max_length=15),
        ),
    ]
