# Generated by Django 5.0.4 on 2024-05-19 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_manager', '0004_user_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsForinstructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=17)),
                ('gender', models.IntegerField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')])),
                ('email', models.EmailField(max_length=254)),
                ('educations', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('applicatoins_date', models.DateTimeField(auto_now=True)),
                ('aproved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['applicatoins_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=17)),
                ('gender', models.IntegerField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')])),
                ('educations', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('ragistraions_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
