# Generated by Django 5.0.4 on 2024-05-19 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_manager', '0007_alter_applicationsforinstructors_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorsprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
