# Generated by Django 5.0.4 on 2024-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_manager', '0010_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='static_files/images/student_image.jpeg', upload_to='images/user_profile_Pic'),
        ),
    ]
