# Generated by Django 5.0.4 on 2024-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts_manager', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'student'), ('instructors', 'instructors'), ('administrator', 'administrator'), ('administrator_instructor', 'administrator_instructor')], default='student', max_length=35),
        ),
    ]
