# Generated by Django 5.0.1 on 2024-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
