# Generated by Django 5.0.1 on 2024-01-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0002_remove_student_id_alter_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
