# Generated by Django 5.0.1 on 2024-01-30 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=200)),
                ('degicnaton', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Maneger',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='a1.employee')),
                ('take_int', models.BooleanField()),
                ('hiring', models.BooleanField()),
            ],
            bases=('a1.employee',),
        ),
    ]
