# Generated by Django 5.0.1 on 2024-01-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0005_friends_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='roll',
            field=models.IntegerField(null=True),
        ),
    ]
