# Generated by Django 5.0.1 on 2024-01-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0006_friends_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('addr', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='friends',
            options={'ordering': ['roll']},
        ),
        migrations.AlterModelOptions(
            name='me',
            options={'ordering': ['roll']},
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('pasNUM', models.IntegerField(primary_key=True, serialize=False)),
                ('total_page', models.IntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a1.people')),
            ],
        ),
    ]
