# Generated by Django 5.0.1 on 2024-01-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0008_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=20)),
                ('stuednts', models.ManyToManyField(to='a1.stu')),
            ],
        ),
    ]
